// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: knowledge.sql

package database

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const deleteFlowMemoryDocuments = `-- name: DeleteFlowMemoryDocuments :exec
DELETE FROM langchain_pg_embedding
WHERE collection_id = (SELECT uuid FROM langchain_pg_collection WHERE name = 'langchain')
  AND COALESCE(cmetadata ->> 'doc_type', '') = 'memory'
  AND (cmetadata ->> 'flow_id') = $1
`

// Delete all memory-type documents for a specific flow.
// Called on flow deletion to free long-term memory that will never be re-used.
// $1 is the decimal text representation of the flow ID (e.g. "55"), matching the
// text result of (cmetadata ->> 'flow_id') which uses JSON ->> extraction.
func (q *Queries) DeleteFlowMemoryDocuments(ctx context.Context, dollar_1 sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteFlowMemoryDocuments, dollar_1)
	return err
}

const deleteKnowledgeDocument = `-- name: DeleteKnowledgeDocument :exec
DELETE FROM langchain_pg_embedding
WHERE uuid::text = $1
  AND collection_id = (SELECT uuid FROM langchain_pg_collection WHERE name = 'langchain')
`

// Delete a knowledge document by UUID (admin — no user_id check).
func (q *Queries) DeleteKnowledgeDocument(ctx context.Context, dollar_1 sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteKnowledgeDocument, dollar_1)
	return err
}

const deleteUserKnowledgeDocument = `-- name: DeleteUserKnowledgeDocument :exec
DELETE FROM langchain_pg_embedding
WHERE uuid::text = $1
  AND (cmetadata ->> 'user_id') = $2
  AND collection_id = (SELECT uuid FROM langchain_pg_collection WHERE name = 'langchain')
`

type DeleteUserKnowledgeDocumentParams struct {
	Column1 sql.NullString `json:"column_1"`
	Column2 sql.NullString `json:"column_2"`
}

// Delete a knowledge document by UUID, only if it belongs to the given user.
func (q *Queries) DeleteUserKnowledgeDocument(ctx context.Context, arg DeleteUserKnowledgeDocumentParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserKnowledgeDocument, arg.Column1, arg.Column2)
	return err
}

const getKnowledgeDocument = `-- name: GetKnowledgeDocument :one
SELECT
  e.uuid::text                              AS id,
  COALESCE(e.document, '')                  AS document,
  COALESCE(e.cmetadata::text, '{}')         AS cmetadata
FROM langchain_pg_embedding e
INNER JOIN langchain_pg_collection c ON e.collection_id = c.uuid
WHERE c.name = 'langchain'
  AND e.uuid::text = $1
`

type GetKnowledgeDocumentRow struct {
	ID        string         `json:"id"`
	Document  string         `json:"document"`
	Cmetadata sql.NullString `json:"cmetadata"`
}

// Fetch a single knowledge document by its UUID (admin view — no user_id check).
func (q *Queries) GetKnowledgeDocument(ctx context.Context, uuid string) (GetKnowledgeDocumentRow, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeDocument, uuid)
	var i GetKnowledgeDocumentRow
	err := row.Scan(&i.ID, &i.Document, &i.Cmetadata)
	return i, err
}

const getUserKnowledgeDocument = `-- name: GetUserKnowledgeDocument :one
SELECT
  e.uuid::text                              AS id,
  COALESCE(e.document, '')                  AS document,
  COALESCE(e.cmetadata::text, '{}')         AS cmetadata
FROM langchain_pg_embedding e
INNER JOIN langchain_pg_collection c ON e.collection_id = c.uuid
WHERE c.name = 'langchain'
  AND e.uuid::text = $1
  AND (e.cmetadata ->> 'user_id') = $2
`

type GetUserKnowledgeDocumentParams struct {
	Uuid      string         `json:"uuid"`
	Cmetadata sql.NullString `json:"cmetadata"`
}

type GetUserKnowledgeDocumentRow struct {
	ID        string         `json:"id"`
	Document  string         `json:"document"`
	Cmetadata sql.NullString `json:"cmetadata"`
}

// Fetch a single knowledge document by UUID, scoped to a specific user.
func (q *Queries) GetUserKnowledgeDocument(ctx context.Context, arg GetUserKnowledgeDocumentParams) (GetUserKnowledgeDocumentRow, error) {
	row := q.db.QueryRowContext(ctx, getUserKnowledgeDocument, arg.Uuid, arg.Cmetadata)
	var i GetUserKnowledgeDocumentRow
	err := row.Scan(&i.ID, &i.Document, &i.Cmetadata)
	return i, err
}

const listAllKnowledgeDocuments = `-- name: ListAllKnowledgeDocuments :many
SELECT
  e.uuid::text                              AS id,
  COALESCE(e.document, '')                  AS document,
  COALESCE(e.cmetadata::text, '{}')         AS cmetadata
FROM langchain_pg_embedding e
INNER JOIN langchain_pg_collection c ON e.collection_id = c.uuid
WHERE c.name = 'langchain'
  AND COALESCE(e.cmetadata ->> 'doc_type', '') NOT IN ('memory')
ORDER BY e.uuid
`

type ListAllKnowledgeDocumentsRow struct {
	ID        string         `json:"id"`
	Document  string         `json:"document"`
	Cmetadata sql.NullString `json:"cmetadata"`
}

// List all knowledge documents excluding the noisy memory type (admin view).
func (q *Queries) ListAllKnowledgeDocuments(ctx context.Context) ([]ListAllKnowledgeDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllKnowledgeDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllKnowledgeDocumentsRow
	for rows.Next() {
		var i ListAllKnowledgeDocumentsRow
		if err := rows.Scan(&i.ID, &i.Document, &i.Cmetadata); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowKnowledgeDocuments = `-- name: ListFlowKnowledgeDocuments :many
SELECT
  e.uuid::text                              AS id,
  COALESCE(e.document, '')                  AS document,
  COALESCE(e.cmetadata::text, '{}')         AS cmetadata
FROM langchain_pg_embedding e
INNER JOIN langchain_pg_collection c ON e.collection_id = c.uuid
WHERE c.name = 'langchain'
  AND COALESCE(e.cmetadata ->> 'doc_type', '') NOT IN ('memory')
  AND (e.cmetadata ->> 'flow_id') = $1
ORDER BY e.uuid
`

type ListFlowKnowledgeDocumentsRow struct {
	ID        string         `json:"id"`
	Document  string         `json:"document"`
	Cmetadata sql.NullString `json:"cmetadata"`
}

// List non-memory knowledge documents belonging to a specific flow (admin scoped).
func (q *Queries) ListFlowKnowledgeDocuments(ctx context.Context, cmetadata sql.NullString) ([]ListFlowKnowledgeDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFlowKnowledgeDocuments, cmetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlowKnowledgeDocumentsRow
	for rows.Next() {
		var i ListFlowKnowledgeDocumentsRow
		if err := rows.Scan(&i.ID, &i.Document, &i.Cmetadata); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserKnowledgeDocuments = `-- name: ListUserKnowledgeDocuments :many
SELECT
  e.uuid::text                              AS id,
  COALESCE(e.document, '')                  AS document,
  COALESCE(e.cmetadata::text, '{}')         AS cmetadata
FROM langchain_pg_embedding e
INNER JOIN langchain_pg_collection c ON e.collection_id = c.uuid
WHERE c.name = 'langchain'
  AND COALESCE(e.cmetadata ->> 'doc_type', '') NOT IN ('memory')
  AND (e.cmetadata ->> 'user_id') = $1
ORDER BY e.uuid
`

type ListUserKnowledgeDocumentsRow struct {
	ID        string         `json:"id"`
	Document  string         `json:"document"`
	Cmetadata sql.NullString `json:"cmetadata"`
}

// List all non-memory knowledge documents owned by a specific user (user-scoped view).
func (q *Queries) ListUserKnowledgeDocuments(ctx context.Context, cmetadata sql.NullString) ([]ListUserKnowledgeDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserKnowledgeDocuments, cmetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserKnowledgeDocumentsRow
	for rows.Next() {
		var i ListUserKnowledgeDocumentsRow
		if err := rows.Scan(&i.ID, &i.Document, &i.Cmetadata); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKnowledgeDocument = `-- name: UpdateKnowledgeDocument :one
UPDATE langchain_pg_embedding
SET
  embedding = $2::vector,
  document  = $3,
  cmetadata = $4::json
WHERE uuid::text = $1
  AND collection_id = (SELECT uuid FROM langchain_pg_collection WHERE name = 'langchain')
RETURNING
  uuid::text                              AS id,
  COALESCE(document, '')                  AS document,
  COALESCE(cmetadata::text, '{}')         AS cmetadata
`

type UpdateKnowledgeDocumentParams struct {
	Column1 sql.NullString        `json:"column_1"`
	Column2 string                `json:"column_2"`
	Column3 sql.NullString        `json:"column_3"`
	Column4 pqtype.NullRawMessage `json:"column_4"`
}

type UpdateKnowledgeDocumentRow struct {
	ID        string         `json:"id"`
	Document  string         `json:"document"`
	Cmetadata sql.NullString `json:"cmetadata"`
}

// Update an existing document's embedding, text and metadata atomically.
// $2 must be formatted as a PostgreSQL vector literal: '[f1,f2,...]'
// $4 must be valid JSON text.
func (q *Queries) UpdateKnowledgeDocument(ctx context.Context, arg UpdateKnowledgeDocumentParams) (UpdateKnowledgeDocumentRow, error) {
	row := q.db.QueryRowContext(ctx, updateKnowledgeDocument,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var i UpdateKnowledgeDocumentRow
	err := row.Scan(&i.ID, &i.Document, &i.Cmetadata)
	return i, err
}
